# Generated by Django 5.0.7 on 2024-09-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_options_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
